### ISSUE TITLE
The calculate of L and M ?

### ISSUE THREAD

**Issue by Jmh0527** [yamahigashi/MayaTransferInpaintWeights#1]
The calculate of L lacks L[i1, i3]? Maybe we should add the followding code?
```
# cotan2 is the angle formed by v2-v1 and v2-v3. 
# This is because the weight of each edge should be the cotan of its corresponding angle.
    L[i1, i3] += cotan2 
    L[i3, i1] += cotan2 
    L[i1, i1] -= cotan2 
    L[i3, i3] -= cotan2 
```

The calculate of M lacks volume of vertex vi.
In the paper,  "M is the diagonal lumped mass matrix (with Voronoi area/volume M𝑖 of vertex 𝑣𝑖 on each diagonal entry 𝑖)".
However, the volume calculation is ignored in your implementation.

**Comment by yamahigashi** [comment]
Thank you for your report ;) I will look into it as soon as I have some time.

**Comment by yamahigashi** [comment]
@Jmh0527 Thank you for pointing out the missing computation.  We have added the necessary code to compute the third cotangent angle and updated the Laplacian matrix entries accordingly: https://github.com/yamahigashi/MayaTransferInpaintWeights/commit/1e88219cc867ecbfe7d54bd19903c7e68307eee7 ;)
