### ISSUE TITLE
Method to Resolve "No module named 'Qt'" Error

### ISSUE THREAD

**Issue by HJYblur** [yamahigashi/MayaTransferInpaintWeights#2]
In case anyone has encountered the same error as me, please go to the ui.py file and replace line 7-25 to the codes below.
This is because Maya has installed PySide2 instead of Qt module acquiescently.
```
from PySide2.QtWidgets import (
    QApplication,
    QWidget,
    QLineEdit,
    QPushButton,
    QLabel,
    QSlider,
    QHBoxLayout,
    QVBoxLayout,
    QRadioButton,
    QGroupBox,
    QSpacerItem,
    QSizePolicy,
)

from PySide2.QtCore import (
    Qt,
    QSize,
)
```

**Comment by yamahigashi** [comment]
Thank you for your reporting :) 
For better compatibility, please use [Qt.py](https://github.com/mottosso/Qt.py)
